version: '3.9'

services:
  # Web (Next.js)
  web:
    build:
      context: .
      dockerfile: ./web/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ../web:/web
    depends_on:
      - api
    environment:
      - API_URL=http://localhost:8000
      - NODE_ENV=development

  # CMS (Vue.js)
  cms:
    build:
      context: .
      dockerfile: ./cms/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ../cms:/app
    depends_on:
      - api
    environment:
      - VITE_API_URL=http://localhost:8000
      - NODE_ENV=development

  # API (Laravel)
  api:
    build:
      context: .
      dockerfile: ./api/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ../api:/var/www/html
    depends_on:
      - database
      - redis
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_CONNECTION=mongodb
      - DB_HOST=database
      - DB_PORT=27017
      - DB_DATABASE=adopt
      - DB_USERNAME=root
      - DB_PASSWORD=root
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  # Database (MongoDB)
  database:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
      - MONGO_INITDB_DATABASE=adopt

  # Redis
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  mongodb_data:
  redis_data:
