services:
  # Web (Nuxt.js 3)
  web:
    build:
      context: ../
      dockerfile: ./adopt-docker/web/Dockerfile
    container_name: adopt-web
    ports:
      - "3000:3000"
    depends_on:
      - api
      - mongo
      - redis
    networks:
      - adopt-network
    volumes:
      - ./adopt-web:/app

  # CMS (Vue.js 3)
  cms:
    build:
      context: ../
      dockerfile: ./adopt-docker/cms/Dockerfile
    container_name: adopt-cms
    ports:
      - "8080:8080"
    depends_on:
      - api
      - mongo
      - redis
    networks:
      - adopt-network
    volumes:
      - ./adopt-cms:/app

  # API (Laravel 11)
  api:
    build:
      context: ../
      dockerfile: ./adopt-docker/api/Dockerfile
    container_name: adopt-api
    ports:
      - "8000:8000"
    depends_on:
      - mongo
      - redis
    networks:
      - adopt-network
    volumes:
      - ./adopt-api:/var/www

  # MongoDB
  mongo:
    image: mongo:latest
    container_name: adopt-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - adopt-network

  # Redis
  redis:
    image: redis:latest
    container_name: adopt-redis
    ports:
      - "6379:6379"
    networks:
      - adopt-network

networks:
  adopt-network:
    driver: bridge

volumes:
  mongo-data:
    driver: local
