version: '3.9'

services:
  # Web (Next.js)
  web:
    build:
      context: ../web
      dockerfile: ../docker_adopt/web/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ../web:/web
    depends_on:
      - api
    environment:
      - API_URL=http://localhost:8000
      - NODE_ENV=development

  # CMS (Vue.js)
  cms:
    build:
      context: ../cms
      dockerfile: ../docker_adopt/cms/Dockerfile
    ports:
      - "80:8080"
    volumes:
      - ../cms:/app
    depends_on:
      - api
    environment:
      - VITE_API_URL=http://localhost:8000
      - NODE_ENV=development

  # API (Laravel)
  api:
    build:
      context: ../api
      dockerfile: ../docker_adopt/api/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ../api:/var/www/html
    depends_on:
      - database
      - redis
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_CONNECTION=mongodb
      - DB_HOST=database
      - DB_PORT=27017
      - DB_DATABASE=adopt
      - DB_USERNAME=root
      - DB_PASSWORD=root
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  # Database (MongoDB)
  database:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
      - MONGO_INITDB_DATABASE=adopt

  # Redis
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  # nginx
  nginx-cms:
    image: nginx:latest
    container_name: adopt_nginx
    ports:
      - "80:80"
      - "81:80"
    volumes:
      - ./nginx/web.conf:/etc/nginx/conf.d/web.conf
      - ./nginx/cms.conf:/etc/nginx/conf.d/cms.conf
      - ../web:/var/www/web
      - ../cms:/var/www/cms
    depends_on:
      - web
      - cms


volumes:
  mongodb_data:
  redis_data:
